### ISSUE TITLE
Closure inside array

### ISSUE THREAD

**Issue by andaniel05** [opis/closure#14]
This is a small representation of my project. I have an App class that collaborate with a symfony event dispatcher. In my environment i have an error with this small equivalent script. My PHP version is 7.1.1. Thanks.

```php
<?php

require_once 'vendor/autoload.php';

use function Opis\Closure\{serialize as s, unserialize as u};

$app = new \stdClass;

$app->dispatcher = [
    'event.name' => [function () use ($app) {}]
];

$text = s($app);
u($text);

```

**Comment by msarca** [comment]
Unfortunately, there are some serious issues regarding arrays, especially the recursive ones. Some of the problems are related to a faulty implementation of the copy-on-write mechanism (even on the newest PHP version, this mechanism seems to be malfunctioning), and others are related to [serialization and recursion](https://bugs.php.net/bug.php?id=72107) issues. We have solutions for some of the problems, but not for all of them. Another source of errors might be the fact that Opis Closure can't currently serialize PHP internal classes, but this will be fixed in a future release. 
In the end we must all remember the library's purpose: closure serialization. Sure, serializing entire arbitrary objects sound nice, but it may prove to be impossible in certain scenarios. So my advice is to [take control](https://github.com/opis/closure/issues/8#issuecomment-272748629) over your serialization process instead of entirely relying on Opis Closure's `serialize` and `unserialize` functions.
I will let this thread open for while, but I will update the documentation and add a disclaimer regarding arbitrary object serialization, asap.
Sorry for the late answer, but it has been a busy week.
