### ISSUE TITLE
Anonymous class serialization

### ISSUE THREAD

**Issue by theofidry** [opis/closure#32]
Is there any way to bring anonymous class serialization in a similar way to closure serialization? For further context: https://github.com/amphp/parallel/issues/79

**Comment by theofidry** [comment]
After some digging, this needs further explanations. `opis/closure` is able to serialize even the unserializable:

```php
use Opis\Closure\SerializableClosure;

class UnserializableClass implements Serializable {
  function serializable() {
    throw new \DomainException();
  }

  function unserializable() {
    throw new \DomainException();
  }
}

unserialize(serialize(new SerializableClosure(
  static function () {
    return new UnserializableClass();
  }
)));

unserialize(serialize(new SerializableClosure(
  static function () {
    return new class() extends stdClass {};
  }
)));
```

However, this is no longer true when it comes to the bindings:

```php
use Opis\Closure\SerializableClosure;

class UnserializableClass implements Serializable {
  function serializable() {
    throw new \DomainException();
  }

  function unserializable() {
    throw new \DomainException();
  }
}

$instance = new UnserializableClass();

$decoratedClosure = static function() use ($instance) {
  return $instance;
}

// Will throw an error (the DomainException one)
unserialize(serialize(new SerializableClosure(decoratedClosure)));

$instance = new class() extends stdClass {};

$decoratedClosure = static function() use ($instance) {
  return $instance;
}

// Will throw an error (Exception anonymous class is not serializable)
unserialize(serialize(new SerializableClosure(decoratedClosure)));
```

Not sure if it can be solved at all...

**Comment by msarca** [comment]
Serializing anonymous classes is a little bit more challenging than closure serialization and it's out of this library's scope. There are a bunch of other things that cannot be serialized, like PDO objects, but they are also out of this library's scope.

> After some digging, this needs further explanations. opis/closure is able to serialize even the unserializable:

The instructions from a function's body are not executed until that function is called. No mystery here, no weird behavior, that's how subroutines work.

> However, this is no longer true when it comes to the bindings:

In order to be able to accurately reconstruct the closure, the variables referenced via `use` are serialized and stored together with the closure's source code. And since the variables used in the provided example are not serializable, an exception is thrown. Perfectly normal and expected.

**Comment by theofidry** [comment]
Figured:)

Thanks for the thorough reply.
