### ISSUE TITLE
Skipping non-user-defined objects/properties

### ISSUE THREAD

**Issue by exteon** [opis/closure#39]
We tried to use `Opis\Closure` to serialize structures that may contain `\Throwable`'s, including system-defined exceptions/errors. In this scenario we expected that the script closure-wrapped the call stack and/or parameters of thrown  exceptions/errors. However, we could only achieve this by removing the `isUserDefined()` restrictions in `SerializableClosure::wrapClosures()`. After which it does work flawlwssly.

Is there a requirement for that restriction? Could it be better fine-tuned/lifted so that we can serialize system throwables?

**Comment by msarca** [comment]
Unfortunately, classes that are defined outside user-land code, often have features that cannot be detected through reflection, simply because these features don't exist in PHP. For example, they might have read-only properties. The only way to overcome this is to treat each case separately, which will result into an extremely time-consuming game of cat and mouse, with minimal benefits.

The way I'm seeing it, is that you have 2 options: you fork `opis/closure` and maintain your own version, fine-tuned for your edge case, or, instead of storing the exception/error object itself, you could store only the relevant data about that object.

```php
class ThrowableData
{
    private $message;
    // ... other properties

    public function __construct(\Throwable $e)
    {
        $this->message = $e->getMessage();
        // .. set other properties
    }
    
    public function getMessage()
    {
        return $this->message;
    }
    
    // .. other methods
}
```

**Comment by exteon** [comment]
Alas, I was wrong, serializing throwables with Opis does mess with the call trace that is regenerated when it tries to deserialize the object. So you can strike this enhancement unless you want to explicitly add throwables serialisation, but it needs some handling on its own to properly repopulate the trace.

**Comment by msarca** [comment]
We are preparing to release a new major version of the library and this should be fixed in the upcoming release. More info #59
