### ISSUE TITLE
Unbinding $this of closure is deprecated on php 7.4

### ISSUE THREAD

**Issue by oleghalin** [opis/closure#84]
The issue is related to that closure was unserialized first, then Closure was serialized again and it doesn't have this attribute. Is there a way to bind $this to newly serialized closure?

basically here is 2 Closures, which I try to serialize. I figured out that issue is related to "isBindingRequired" is false for a second.

![image](https://user-images.githubusercontent.com/9086983/97575566-960c4300-19f5-11eb-9775-5113b99fe0c0.png)
![image](https://user-images.githubusercontent.com/9086983/97575570-986e9d00-19f5-11eb-9ed5-86c7f76b4eec.png)

**Comment by aliwesome** [comment]
I have same issue.

**Comment by e1himself** [comment]
Same issue. Had to rewrite the code without using `$this`.

**Comment by e1himself** [comment]
I've narrowed the root cause to the fact that `isBindingRequired` property is calculated during `ReflectionClosure::getCode()` parsing. But parsing is skipped altogether when you get a reflector for an unserialized `SerializedClosure` that already has non-null `$code` value:

https://github.com/opis/closure/blob/628cc7645d38d7d443bb35fd5480e910350af67c/src/SerializableClosure.php#L89-L102

https://github.com/opis/closure/blob/628cc7645d38d7d443bb35fd5480e910350af67c/src/ReflectionClosure.php#L31-L41

**Comment by oleghalin** [comment]
Yeah, i saw it too. It will be serialized, but `$this` will not be attach as scope to new serialized closure.

**Comment by e1himself** [comment]
Thanks a lot @msarca! :tada:
